# Kustomization - Base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-wiki

resources:
  - namespace.yaml
  - deployments.yaml
  - config-ingress.yaml

commonLabels:
  app.kubernetes.io/name: rag-wiki
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
